### ISSUE TITLE
[conflicts] Ensure repo is clean before push/pr phase

### ISSUE THREAD

**Issue by spalger** [sqren/backport-cli#22]
When conflicts are found during a cherry-pick the backport tool pauses, but it doesn't verify the user input when they say that the conflict has been resolved. If the conflict has been resolved but the cherry-pick has not been `--continue`'d an incomplete pr is pushed to the user's fork and pull requested.

I think that when the user answers `"Have you solved the merge conflict?"` with `Y` the backport tool should verify that the repo is not dirty and that there is no cherry-pick/rebase/merge pending.

It would also be nice if the `"Have you solved the merge conflict?"` message offered a `?` input that described the steps the user should take in more detail, and offered these instructions to the user in case they have not handled conflicts in a backport before.

**Comment by sqren** [comment]
This could definitely be improved. Going on vacation next week but I'll try to get it done sometime after.
