### ISSUE TITLE
Add `backport` label on repos where it exists

### ISSUE THREAD

**Issue by epixa** [sqren/backport-cli#6]
It's really useful for glancing at a list of PRs or auditing PRs to be able to filter away any PR that has a `backport` label, so it'd be great if this tool added that label automatically to all backport PRs.

**Comment by sqren** [comment]
I tried doing this, but Github's API didn't seem to let me add labels to PRs. Will make this a priority now.

**Comment by epixa** [comment]
You may want to take a look at the elastic-jasper github code to see how I did it there. I can't remember off-hand

**Comment by sqren** [comment]
@epixa I've created a PR https://github.com/sqren/backport-cli/pull/12 that allows the user to labels to their config file, which will be added to the backport PR. Like this:

```json
{
  "name": "elastic/kibana",
  "versions": ["6.x", "6.0", "5.6", "5.5", "5.4"],
  "labels": ["backport"]
}
```

I also considered making it a handler like (although that seems unnecessary for now)
```json
{
  "name": "elastic/kibana",
  "versions": ["6.x", "6.0", "5.6", "5.5", "5.4"],
  "labels": version => {
    return something ? ["backport", version] : [version];
  }
}
```
