### ISSUE TITLE
Prefix backport PRs with [<branch>] rather than [backport]

### ISSUE THREAD

**Issue by epixa** [sqren/backport-cli#7]
Having some sort of meaningful indication on a PR that it is a backport is helpful, but it doesn't necessarily need to be the word "backport" in the title.  The convention of putting the target backport branch as a prefix on the backport PR title would still be recognized by people using this tool frequently, and the [backport label](https://github.com/sqren/backport-cli/issues/6) could be the thing that says the word "backport" in case people want that.

Using the branch prefix really helps with auditing PRs to ensure that they were properly backported since you'd have all of the necessary information you need about the PRs right in the linkbacks in the original PR.

For example, these linked backport PRs would be much more useful if they instead began with their target branch:

![screen shot 2017-10-24 at 4 52 18 pm](https://user-images.githubusercontent.com/53814/31967414-dc218194-b8db-11e7-8b1a-c0858670d486.png)

**Comment by epixa** [comment]
This is how it would look in the PR list using both the backport label and the branch prefix:

![screen shot 2017-10-24 at 4 54 26 pm](https://user-images.githubusercontent.com/53814/31967494-0df5c522-b8dc-11e7-9b6a-50111e85c3ed.png)

**Comment by sqren** [comment]
Makes sense. This should be an easy fix.
